title: My Demo Page
author: Adeola Omonira
email: ms.omonira@gmail.com
theme: minima
description: > # this means to ignore newlines until "baseurl:"
  Demo Website, with Lorem Ipsum content to test.

# social links
twitter_username: your-twitter-handle
github_username:  addyapproved

show_excerpts: true # set to false to remove excerpts on the homepage
